### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by tekktrik** [circuitpython/CircuitPython_Org_DisplayIO_Gauge#2]
It looks like the documentation isn't available via the badge on the README

**Comment by tekktrik** [comment]
Actually, it may not be in ReadTheDocs at all, heads up @FoamyGuy

**Comment by tekktrik** [comment]
Hey @FoamyGuy if you have permissions to setup webhooks for circuitpython_org, I think setting it up for this library should resolve it!

**Comment by FoamyGuy** [comment]
I'm catching up on this one I missed the prior notifications from it. Thanks for bringing this one up and getting the docs started.

It looks like this on RTD now, I'm guessing you created it? I can click this badge in the readme and it does take me to the docs: 
![image](https://user-images.githubusercontent.com/2406189/170833342-7cd2328f-cb75-4ae1-9aee-f7ec93f74e3a.png)

I do have permissions to add the webhook on the github side. But I don't have permission on the RTD side to get to the admin page to set up the "integration" on that side so that I can get the URL to put into the github webhook config.

@tekktrik can you add circuitpython (https://readthedocs.org/profiles/circuitpython/) and me (https://readthedocs.org/profiles/foamyguy/) as maintainers to https://readthedocs.org/projects/circuitpython-displayio-gauge/builds/?

Once I have access to the admin there I can fill in the webhook on the github side.

**Comment by tekktrik** [comment]
All set!

**Comment by tekktrik** [comment]
Hey @FoamyGuy were you able to add the webhook?

**Comment by FoamyGuy** [comment]
@tekktrik, yep I believe it's all set now. It shows the initial sync on the RTD side.
![image](https://user-images.githubusercontent.com/2406189/173970889-c028903c-dc0a-42ff-8b44-6d0eb42eacbc.png)
